# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Development Server
  config.vm.define "{{ cookiecutter.app_name }}-dev", primary: true do |dev|
    dev.vm.provider :virtualbox do |virtualbox|
      virtualbox.customize ["modifyvm", :id, "--memory", "384"]
      virtualbox.customize ["modifyvm", :id, "--cpus", "1"]
    end
    dev.vm.hostname = "{{ cookiecutter.app_name }}-dev"
    dev.vm.box = "ubuntu/trusty64"
    dev.vm.network "private_network", ip: "{{ cookiecutter.vagrant_ipv4 }}"
    dev.vm.provision :ansible do |ansible|
      ansible.playbook = "playbooks/develop.yml"
      ansible.inventory_path = "playbooks/hosts"
      # ansible.ask_vault_pass = true
      ansible.limit = "all"
    end
  end

end
